spring:
  application:
    name: api-gateway
  devtools:
    livereload.enabled: true
    restart.enabled: true

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
          filters:
            - AddRequestHeader=X-Request-ID, 12345
            - AddResponseHeader=X-Response-ID, 67890
            - RewritePath=/user/(?<segment>.*), /newuser/${segment}
            - RedirectTo=302, http://localhost:8081/tmp
        - id: product
          uri: http://localhost:8082
          predicates:
            - Path=/prod/**
server:
  port: 80
