spring:
  application:
    name: api-gateway
  devtools:
    livereload.enabled: true
    restart.enabled: true

  cloud:
    gateway:
      routes:
        - id: user
          # docker conainer 주소
          uri: http://api1:8081
          predicates:
            - Path=/user/**
        - id: product
          # docker conainer 주소
          uri: http://api2:8082
          predicates:
            - Path=/prod/**
       #   filters:
            # MSA 별 필터 정의할 수 있음
      # 전역 필터(게이트웨이에서 전후에 무조건 타게 함)
      #default-filters:
server:
  port: 80
