spring:
  application:
    name: api-gateway
  devtools:
    livereload.enabled: true
    restart.enabled: true

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
          filters:
            - name: L1Filter
              args:
                pre: true
                post: true
            - name: L2Filter
              args:
                pre: true
                post: true
        - id: product
          uri: http://localhost:8082
          predicates:
            - Path=/prod/**
server:
  port: 80
