server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: prod
  devtools:
    livereload.enabled: true
    restart.enabled: true
