server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: user
  devtools:
    livereload.enabled: true
    restart.enabled: true
